export const G = {
  cardDraft: {},
  cardEditorEventId: null,
  lmap: null,
  hostMap: null,
  newEventLat: null,
  MAPBOX_TOKEN: null,
  geocodeCache: {},
  _signupType: 'attendee',
  _hostCats: [],
  _authMode: 'login',
  navStack: [],
  chatSubscriptions: {},
  activePopup: null,
  htmlMarkerRefs: {},
  searchSessionToken: null,
  autocompleteTimeout: null,
  _odCur: 'Live',
  ownerLiveData: null,
  _ownerLiveLoading: false,
  _sheenHandler: null,
  myTickets: [],
  bookingDraft: null,
  _socialSeenCount: {},
  _hostType: 'Indie'
};
