#!/usr/bin/env node
/**
 * build-env.mjs — generates src/js/env.js from .env (or process env vars).
 *
 * Zero dependencies. Run from the repo root:
 *   node scripts/build-env.mjs
 *
 * In CI (e.g. GitHub Actions deploying Pages), skip the .env file and export
 * the variables as job env/secrets — process.env wins over .env here, so:
 *   SUPABASE_URL: ${{ vars.SUPABASE_URL }}
 *   SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
 *   MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ENV_FILE = join(ROOT, '.env');
const OUT_FILE = join(ROOT, 'src', 'js', 'env.js');

const KEYS = ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'MAPBOX_ACCESS_TOKEN'];

// ── Parse .env if present (KEY=VALUE lines, # comments, optional quotes) ────
const fileVars = {};
if (existsSync(ENV_FILE)) {
  for (const rawLine of readFileSync(ENV_FILE, 'utf8').split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    fileVars[key] = val;
  }
}

// ── Resolve: process.env (CI) beats .env (local dev) ────────────────────────
const resolved = {};
const missing = [];
for (const key of KEYS) {
  const value = process.env[key] || fileVars[key] || '';
  if (!value || value.startsWith('your-') || value.includes('your-project-ref')) {
    missing.push(key);
  }
  resolved[key] = value;
}

const banner = missing.length
  ? `// ⚠ Generated with MISSING values: ${missing.join(', ')} — app will run in degraded mode.`
  : '// Generated by scripts/build-env.mjs — DO NOT EDIT, DO NOT COMMIT.';

const out = `${banner}
// Regenerate with: node scripts/build-env.mjs
window.__CUMULUS_ENV__ = Object.freeze(${JSON.stringify(resolved, null, 2)});
`;

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, out, 'utf8');

console.log(`✓ wrote ${OUT_FILE}`);
if (missing.length) {
  console.warn(`⚠ missing values for: ${missing.join(', ')}`);
  console.warn('  → copy .env.example to .env and fill them in, then re-run.');
  process.exitCode = 1;
}
